spring.application.name=BusBookingApp
spring.datasource.url=jdbc:postgresql://localhost:5432/busbookingapp
spring.datasource.username=kather
spring.datasource.password=kather
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
# Initialize the database with schema.sql on startup. Values can be 'always', 'never', or 'embedded'. 'always' will run the script regardless of the database type, 'never' will never run it, and 'embedded' will only run it for embedded databases.
spring.sql.init.mode=never
spring.sql.init.schema-locations=classpath:schema.sql

# Allow detailed error messages in responses
spring.web.error.include-message=always

spring.profiles.active=testing

